In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
%matplotlib inline
import matplotlib
matplotlib.rcParams["figure.figsize"] = (20,10)


In [2]:
df1 = pd.read_csv("C:\\Users\\Rohit\\PycharmProjects\\Pycharm Projects\\MultivariateLinearRegression\\homeprices.csv")
df1.head()


area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [3]:
import math
median_bedrooms = math.floor(df1.bedrooms.median())
median_bedrooms

4

In [4]:
df1.bedrooms = df1.bedrooms.fillna(median_bedrooms)
df1

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [5]:
from sklearn import linear_model
reg = linear_model.LinearRegression()

In [6]:
reg.fit(df1[['area','bedrooms','age']],df1.price)

LinearRegression()

In [7]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [8]:
reg.predict([[3000,3,40]])

array([498408.25158031])

In [9]:
reg.predict([[2500,4,5]])

array([578876.03748933])

In [10]:
df2 = pd.read_csv("C:\\Users\\Rohit\\PycharmProjects\\Pycharm Projects\\MultivariateLinearRegression\\hiring.csv")
df2

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [11]:
test_score_mean = math.floor(df2.test_score.mean())
test_score_mean

7

In [12]:
df2.test_score = df2.test_score.fillna(test_score_mean)
df2

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         7.0                7   72000
7     eleven         7.0                8   80000

In [13]:
from sklearn import linear_model
reg2 = linear_model.LinearRegression()

In [14]:
reg2.fit(df2[['test_score','interview_score']],df2.salary)

LinearRegression()

In [16]:
reg2.predict([[9,9]])

array([62443.91408115])